### ISSUE TITLE
memory leak on search

### ISSUE THREAD

**Issue by danilos** [richardwilly98/es-dms#21]
when running memory searches it appears that there is a memory leak. An identical repeated search with search criteria uses the following memory (all amounts in MB):

start, no search: es = 124 es-dms = 293
searches:
1st es = 590 es-dms = 553
2nd es = 650 es-dms = 595
3rd es = 751 es-dms = 592
4th es = 842 es-dms = 581 **\* es-dms-site crash!

reloaded web page, re-logged in
start es = 842 es-dms = 582
1st es = 932->921 ed-dms = 650 -> 582 (max memory reached GC kicked in)

**Comment by danilos** [comment]
memory leak persists on the web client. performing multiple searches gradually increases memory use. es process remains stable but console recorded several issues with connection:

[2013-06-23 10:28:59,869][WARN ][cluster.service          ] [Andreas von Strucker] failed to reconnect to node [Andreas von Strucker][wQmm7FcjR9GgFS-blg460A][inet[/192.168.40.165:9300]]
org.elasticsearch.transport.ConnectTransportException: [Andreas von Strucker][inet[/192.168.40.165:9300]] connect_timeout[30s]
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
        at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:401)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.ConnectException: Connection timed out: no further information: /192.168.40.165:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        ... 3 more
[2013-06-23 10:32:05,943][WARN ][cluster.service          ] [Andreas von Strucker] failed to reconnect to node [Andreas von Strucker][wQmm7FcjR9GgFS-blg460A][inet[/192.168.40.165:9300]]
org.elasticsearch.transport.ConnectTransportException: [Andreas von Strucker][inet[/192.168.40.165:9300]] connect_timeout[30s]
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
        at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:401)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.ConnectException: Connection timed out: no further information: /192.168.40.165:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        ... 3 more
[2013-06-23 10:35:12,084][WARN ][cluster.service          ] [Andreas von Strucker] failed to reconnect to node [Andreas von Strucker][wQmm7FcjR9GgFS-blg460A][inet[/192.168.40.165:9300]]
org.elasticsearch.transport.ConnectTransportException: [Andreas von Strucker][inet[/192.168.40.165:9300]] connect_timeout[30s]
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
        at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:401)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.ConnectException: Connection timed out: no further information: /192.168.40.165:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        ... 3 more
[2013-06-23 10:38:18,184][WARN ][cluster.service          ] [Andreas von Strucker] failed to reconnect to node [Andreas von Strucker][wQmm7FcjR9GgFS-blg460A][inet[/192.168.40.165:9300]]
org.elasticsearch.transport.ConnectTransportException: [Andreas von Strucker][inet[/192.168.40.165:9300]] connect_timeout[30s]
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
        at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:401)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.ConnectException: Connection timed out: no further information: /192.168.40.165:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        ... 3 more
[2013-06-23 10:41:24,463][WARN ][cluster.service          ] [Andreas von Strucker] failed to reconnect to node [Andreas von Strucker][wQmm7FcjR9GgFS-blg460A][inet[/192.168.40.165:9300]]
org.elasticsearch.transport.ConnectTransportException: [Andreas von Strucker][inet[/192.168.40.165:9300]] connect_timeout[30s]
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
        at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:401)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.ConnectException: Connection timed out: no further information: /192.168.40.165:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        ... 3 more
[2013-06-23 10:44:30,918][WARN ][cluster.service          ] [Andreas von Strucker] failed to reconnect to node [Andreas von Strucker][wQmm7FcjR9GgFS-blg460A][inet[/192.168.40.165:9300]]
org.elasticsearch.transport.ConnectTransportException: [Andreas von Strucker][inet[/192.168.40.165:9300]] connect_timeout[30s]
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
        at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:401)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.ConnectException: Connection timed out: no further information: /192.168.40.165:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        ... 3 more
[2013-06-23 10:47:37,125][WARN ][cluster.service          ] [Andreas von Strucker] failed to reconnect to node [Andreas von Strucker][wQmm7FcjR9GgFS-blg460A][inet[/192.168.40.165:9300]]
org.elasticsearch.transport.ConnectTransportException: [Andreas von Strucker][inet[/192.168.40.165:9300]] connect_timeout[30s]
        at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:671)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:610)
        at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:580)
        at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:127)
        at org.elasticsearch.cluster.service.InternalClusterService$ReconnectToNodes.run(InternalClusterService.java:401)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.net.ConnectException: Connection timed out: no further information: /192.168.40.165:9300
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:692)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)

**Comment by danilos** [comment]
what is this Andreas von Strucker?

**Comment by danilos** [comment]
![chrome es client memory leak](https://f.cloud.github.com/assets/4184485/691735/5e1eb1f4-dbb8-11e2-8d53-b4b519cf4699.jpg)
