### ISSUE TITLE
Exception in elasticSearch when generating preview

### ISSUE THREAD

**Issue by danilos** [richardwilly98/es-dms#33]
Elasticsearch generates an exception when user hoovers on a document in es-dms result list trying to generate a preview. Apparently for certain binary formats it is unable to extract first 100000 characters.

Log files follows

in between the exceptions there is huge binary output

**Comment by danilos** [comment]
Tz2AABD9/8AqPIAALb4/wHwNvYAAIn3/wBd9gABWvz4/wCK+AABL7/6//7/Bv2WDAAAMev4/wC7+ACBAAQAH0ySp/6kA6iTTiL0AAIpoaL6oAKpbwP0AAIDf6/6qwKupCj2AAFir/mrAbBD9gACQqut+qsBtGL3AAITet78////AtVbBv4AAiOfrPqpAa2C+ACBAN0A/wH0AAAB6wAAAeoAAAHqAAUZV6Orqa0CoVcZ5wCBAIEA5ACBAIE
A5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5ACBAIEA5AA=","_content_type":"application/octet-stream","_name":"informa-logo-bmp.psd"},"name":"1","current":tru
e,"version_id":1}],"attributes":{"author":"admin","creation":"2013-06-27T15:06:47.663+07:00","status":"A","modified":"2013-06-27T15:06:47.665+07:00"}}]}]
org.elasticsearch.index.mapper.MapperParsingException: Failed to extract [100000] characters of text for [informa-logo-bmp.psd]
        at org.elasticsearch.index.mapper.attachment.AttachmentMapper.parse(AttachmentMapper.java:316)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:515)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:457)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:515)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeArray(ObjectMapper.java:577)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:459)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:506)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:450)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:326)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:203)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:532)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.start(TransportShardReplicationOperationAction.java:434)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.start(TransportShardReplicationOperationAction.java:343)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction.doExecute(TransportShardReplicationOperationAction.java:107)
        at org.elasticsearch.action.index.TransportIndexAction.innerExecute(TransportIndexAction.java:136)
        at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:118)
        at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:68)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:61)
        at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:352)
        at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:211)
        at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:85)
        at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$AsyncSingleAction$1.run(TransportInstanceSingleOperationAction.java:191)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.tika.exception.TikaException: Invalid Image Resource Block Signature Found, got 3686985 0x384249 but the spec defines 943868237
        at org.apache.tika.parser.image.PSDParser$ResourceBlock.<init>(PSDParser.java:154)
        at org.apache.tika.parser.image.PSDParser$ResourceBlock.<init>(PSDParser.java:138)
        at org.apache.tika.parser.image.PSDParser.parse(PSDParser.java:113)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:242)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:242)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
        at org.apache.tika.Tika.parseToString(Tika.java:421)
        at org.elasticsearch.index.mapper.attachment.AttachmentMapper.parse(AttachmentMapper.java:314)
        ... 24 more
[2013-06-27 15:06:50,069][DEBUG][action.index             ] [Manbot] [es-dms][3], node[37kY_GJWRnuCTWS68sZ9KA], [P], s[STARTED]: Failed to execute [index {[es-dms][document][6c84f54a-f82d-434b-95bd-d3a1f42833d1], source[{"id":"6c84f54a-f82d-434b-95bd
-d3a1f42833d1","name":"C:\dev\temp\informa-logo.psd","versions":[{"document_id":"6c84f54a-f82d-434b-95bd-d3a1f42833d1","file":{"content":"OEJQUwABAAAAAAAAAAQAAADcAAABHQAQAAMAAAAAAABt5jhCSU0EJQAAAAAAEAAAAAAAAAAAAAAAAAAAAAA4QklNBCQAAAAAQVs8P3hwYWNrZ

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","_con
tent_type":"application/octet-stream","_name":"informa-logo.psd"},"name":"1","current":true,"version_id":1}],"attributes":{"author":"admin","creation":"2013-06-27T15:06:49.742+07:00","status":"A","modified":"2013-06-27T15:06:49.744+07:00"}}]}]
org.elasticsearch.index.mapper.MapperParsingException: Failed to extract [100000] characters of text for [informa-logo.psd]
        at org.elasticsearch.index.mapper.attachment.AttachmentMapper.parse(AttachmentMapper.java:316)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:515)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:457)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:515)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeArray(ObjectMapper.java:577)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:459)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:506)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:450)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:326)
        at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:203)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:532)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.start(TransportShardReplicationOperationAction.java:434)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.start(TransportShardReplicationOperationAction.java:343)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction.doExecute(TransportShardReplicationOperationAction.java:107)
        at org.elasticsearch.action.index.TransportIndexAction.innerExecute(TransportIndexAction.java:136)
        at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:118)
        at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:68)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:61)
        at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:352)
        at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:211)
        at org.elasticsearch.action.update.TransportUpdateAction.shardOperation(TransportUpdateAction.java:85)
        at org.elasticsearch.action.support.single.instance.TransportInstanceSingleOperationAction$AsyncSingleAction$1.run(TransportInstanceSingleOperationAction.java:191)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.tika.exception.TikaException: Invalid Image Resource Block Signature Found, got 3686985 0x384249 but the spec defines 943868237
        at org.apache.tika.parser.image.PSDParser$ResourceBlock.<init>(PSDParser.java:154)
        at org.apache.tika.parser.image.PSDParser$ResourceBlock.<init>(PSDParser.java:138)
        at org.apache.tika.parser.image.PSDParser.parse(PSDParser.java:113)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:242)
        at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:242)
        at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:120)
        at org.apache.tika.Tika.parseToString(Tika.java:421)
        at org.elasticsearch.index.mapper.attachment.AttachmentMapper.parse(AttachmentMapper.java:314)
        ... 24 more
[2013-06-27 15:06:50,753][DEBUG][action.index             ] [Manbot] [es-dms][1], node[37kY_GJWRnuCTWS68sZ9KA], [P], s[STARTED]: Failed to execute [index {[es-dms][document][14c4543a-be5e-4490-adb7-23eab645898f], source[{"id":"14c4543a-be5e-4490-adb7
-23eab645898f","name":"C:\dev\temp\informa-logo_10.psd","versions":[{"document_id":"14c4543a-be5e-4490-adb7-23eab645898f","file":{"content":"OEJQUwABAAAAAAAAAAQAAABCAAAAVgAQAAMAAAAAAABrUjhCSU0EJQAAAAAAEAAAAAAAAAAAAAAAAAAAAAA4QklNBCQAAAAASGQ8P3hwYW

**Comment by richardwilly98** [comment]
@danilos 
Can you please re-test with the new preview implementation?
